### ISSUE TITLE
boost patch file missing

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-camera-calibration-parsers#5]
@bionade24  The patch file referenced in 992780f10c49bb1acba1b19e715eee2aee7e2bed seems to be missing.

**Comment by bionade24** [comment]
I wrote the script changing that a bit too fast and didn't checked it's impact. I  know there quite a few other things still broken and a lot has already been fixed. But I don't have any motivation and until now no one complained, so I guess holidays give a bit of time. I hope this is the last big commitment to those packages I have to make.

**Comment by bionade24** [comment]
Fixed in 724639e

**Comment by fmauch** [comment]
In fact, the package built without the patch at all, as the library is still called `libboost-python3.so`. I removed it in 12dd02d.

**Comment by bionade24** [comment]
Oh no remote rejected will fix it.

**Comment by bionade24** [comment]
I had to force-push, hope you default handling for git pull conflicts is rebase.

**Comment by fmauch** [comment]
sure thing!
